/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjectController;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Project;

/**
 *
 * @author alecm
 */
public class InsertProjectFrame extends javax.swing.JDialog {

    ProjectController projectController;

    public InsertProjectFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        projectController = new ProjectController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertProjectContainer = new javax.swing.JPanel();
        InsertProjectHeader = new javax.swing.JPanel();
        InsertProjectTitle = new javax.swing.JLabel();
        InsertProjectActionContainer = new javax.swing.JLayeredPane();
        checkIcon = new javax.swing.JLabel();
        insertLabel = new javax.swing.JLabel();
        InsertProjectFieldsContainer = new javax.swing.JPanel();
        InsertProjectNameField = new javax.swing.JTextField();
        InsertProjectDescriptionField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(420, 350));

        InsertProjectContainer.setBackground(new java.awt.Color(255, 255, 255));
        InsertProjectContainer.setMinimumSize(new java.awt.Dimension(400, 320));
        InsertProjectContainer.setPreferredSize(new java.awt.Dimension(400, 320));

        InsertProjectHeader.setBackground(new java.awt.Color(50, 159, 186));

        InsertProjectTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        InsertProjectTitle.setForeground(java.awt.Color.white);
        InsertProjectTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InsertProjectTitle.setText("Project");

        InsertProjectActionContainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertProjectActionContainerMouseClicked(evt);
            }
        });

        checkIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N

        insertLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insertLabel.setForeground(java.awt.Color.white);
        insertLabel.setLabelFor(checkIcon);
        insertLabel.setText("Insert");

        InsertProjectActionContainer.setLayer(checkIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertProjectActionContainer.setLayer(insertLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout InsertProjectActionContainerLayout = new javax.swing.GroupLayout(InsertProjectActionContainer);
        InsertProjectActionContainer.setLayout(InsertProjectActionContainerLayout);
        InsertProjectActionContainerLayout.setHorizontalGroup(
            InsertProjectActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertProjectActionContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(InsertProjectActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkIcon)))
        );
        InsertProjectActionContainerLayout.setVerticalGroup(
            InsertProjectActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertProjectActionContainerLayout.createSequentialGroup()
                .addComponent(insertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(checkIcon)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout InsertProjectHeaderLayout = new javax.swing.GroupLayout(InsertProjectHeader);
        InsertProjectHeader.setLayout(InsertProjectHeaderLayout);
        InsertProjectHeaderLayout.setHorizontalGroup(
            InsertProjectHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertProjectHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertProjectActionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        InsertProjectHeaderLayout.setVerticalGroup(
            InsertProjectHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertProjectHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsertProjectHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertProjectHeaderLayout.createSequentialGroup()
                        .addComponent(InsertProjectTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(InsertProjectActionContainer))
                .addContainerGap())
        );

        InsertProjectFieldsContainer.setBackground(java.awt.Color.white);
        InsertProjectFieldsContainer.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(50, 159, 186)));

        InsertProjectNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Project Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 159, 186))); // NOI18N
        InsertProjectNameField.setOpaque(true);

        InsertProjectDescriptionField.setColumns(20);
        InsertProjectDescriptionField.setLineWrap(true);
        InsertProjectDescriptionField.setRows(5);
        InsertProjectDescriptionField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Project Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 159, 186))); // NOI18N

        javax.swing.GroupLayout InsertProjectFieldsContainerLayout = new javax.swing.GroupLayout(InsertProjectFieldsContainer);
        InsertProjectFieldsContainer.setLayout(InsertProjectFieldsContainerLayout);
        InsertProjectFieldsContainerLayout.setHorizontalGroup(
            InsertProjectFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertProjectFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsertProjectFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsertProjectNameField)
                    .addComponent(InsertProjectDescriptionField))
                .addContainerGap())
        );
        InsertProjectFieldsContainerLayout.setVerticalGroup(
            InsertProjectFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertProjectFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertProjectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertProjectDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InsertProjectContainerLayout = new javax.swing.GroupLayout(InsertProjectContainer);
        InsertProjectContainer.setLayout(InsertProjectContainerLayout);
        InsertProjectContainerLayout.setHorizontalGroup(
            InsertProjectContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertProjectHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(InsertProjectContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertProjectFieldsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        InsertProjectContainerLayout.setVerticalGroup(
            InsertProjectContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertProjectContainerLayout.createSequentialGroup()
                .addComponent(InsertProjectHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InsertProjectFieldsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertProjectContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertProjectContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertProjectActionContainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertProjectActionContainerMouseClicked

        try {

            if (!InsertProjectNameField.getText().equals("") && !InsertProjectDescriptionField.getText().equals("")) {
                Project project = new Project();
                project.setProjectName(InsertProjectNameField.getText());
                project.setProjectDescription(InsertProjectDescriptionField.getText());
                projectController.save(project);
                JOptionPane.showMessageDialog(rootPane, "Project saved");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "All fields are required!");
            }

        } catch (HeadlessException | SQLException exception) {
            JOptionPane.showMessageDialog(rootPane, exception.getMessage());
        }

    }//GEN-LAST:event_InsertProjectActionContainerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InsertProjectFrame dialog = new InsertProjectFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane InsertProjectActionContainer;
    private javax.swing.JPanel InsertProjectContainer;
    private javax.swing.JTextArea InsertProjectDescriptionField;
    private javax.swing.JPanel InsertProjectFieldsContainer;
    private javax.swing.JPanel InsertProjectHeader;
    private javax.swing.JTextField InsertProjectNameField;
    private javax.swing.JLabel InsertProjectTitle;
    private javax.swing.JLabel checkIcon;
    private javax.swing.JLabel insertLabel;
    // End of variables declaration//GEN-END:variables
}
