/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;
import util.ValidateFields;
import view.MainJFrame;

/**
 *
 * @author alecm
 */
public class InsertTaskFrame extends javax.swing.JDialog {

    ProjectController projectController;
    TaskController taskController;
    Project project;

    public InsertTaskFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        projectController = new ProjectController();
        taskController = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertTaskContainer = new javax.swing.JPanel();
        InsertTaskHeader = new javax.swing.JPanel();
        InsertTaskTitle = new javax.swing.JLabel();
        InsertTaskActionContainer = new javax.swing.JLayeredPane();
        checkIcon = new javax.swing.JLabel();
        insertLabel = new javax.swing.JLabel();
        InsertTaskFieldsContainer = new javax.swing.JPanel();
        InsertTaskNameField = new javax.swing.JTextField();
        InsertTaskDescriptionField = new javax.swing.JTextArea();
        InsertTaskDeadlineField = new javax.swing.JFormattedTextField();
        InsertTaskCommentField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 520));

        InsertTaskContainer.setBackground(new java.awt.Color(255, 255, 255));
        InsertTaskContainer.setMinimumSize(new java.awt.Dimension(400, 320));

        InsertTaskHeader.setBackground(new java.awt.Color(50, 159, 186));

        InsertTaskTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        InsertTaskTitle.setForeground(java.awt.Color.white);
        InsertTaskTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InsertTaskTitle.setText("Task");

        InsertTaskActionContainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertTaskActionContainerMouseClicked(evt);
            }
        });

        checkIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N

        insertLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insertLabel.setForeground(java.awt.Color.white);
        insertLabel.setText("Insert");

        InsertTaskActionContainer.setLayer(checkIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTaskActionContainer.setLayer(insertLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout InsertTaskActionContainerLayout = new javax.swing.GroupLayout(InsertTaskActionContainer);
        InsertTaskActionContainer.setLayout(InsertTaskActionContainerLayout);
        InsertTaskActionContainerLayout.setHorizontalGroup(
            InsertTaskActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTaskActionContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(InsertTaskActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkIcon)))
        );
        InsertTaskActionContainerLayout.setVerticalGroup(
            InsertTaskActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTaskActionContainerLayout.createSequentialGroup()
                .addComponent(insertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(checkIcon)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout InsertTaskHeaderLayout = new javax.swing.GroupLayout(InsertTaskHeader);
        InsertTaskHeader.setLayout(InsertTaskHeaderLayout);
        InsertTaskHeaderLayout.setHorizontalGroup(
            InsertTaskHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTaskHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertTaskTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertTaskActionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        InsertTaskHeaderLayout.setVerticalGroup(
            InsertTaskHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTaskHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsertTaskHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertTaskHeaderLayout.createSequentialGroup()
                        .addComponent(InsertTaskTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(InsertTaskActionContainer))
                .addContainerGap())
        );

        InsertTaskFieldsContainer.setBackground(java.awt.Color.white);
        InsertTaskFieldsContainer.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(50, 159, 186)));

        InsertTaskNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Task Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 159, 186))); // NOI18N
        InsertTaskNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertTaskNameFieldActionPerformed(evt);
            }
        });

        InsertTaskDescriptionField.setColumns(20);
        InsertTaskDescriptionField.setLineWrap(true);
        InsertTaskDescriptionField.setRows(5);
        InsertTaskDescriptionField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Task Comments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 159, 186))); // NOI18N

        InsertTaskDeadlineField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Task Deadline", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 159, 186))); // NOI18N
        InsertTaskDeadlineField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        InsertTaskDeadlineField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertTaskDeadlineFieldActionPerformed(evt);
            }
        });

        InsertTaskCommentField.setColumns(20);
        InsertTaskCommentField.setLineWrap(true);
        InsertTaskCommentField.setRows(5);
        InsertTaskCommentField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Task Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 159, 186))); // NOI18N

        javax.swing.GroupLayout InsertTaskFieldsContainerLayout = new javax.swing.GroupLayout(InsertTaskFieldsContainer);
        InsertTaskFieldsContainer.setLayout(InsertTaskFieldsContainerLayout);
        InsertTaskFieldsContainerLayout.setHorizontalGroup(
            InsertTaskFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertTaskDescriptionField)
            .addComponent(InsertTaskNameField)
            .addComponent(InsertTaskCommentField)
            .addComponent(InsertTaskDeadlineField)
        );
        InsertTaskFieldsContainerLayout.setVerticalGroup(
            InsertTaskFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTaskFieldsContainerLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(InsertTaskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertTaskCommentField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertTaskDeadlineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertTaskDescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout InsertTaskContainerLayout = new javax.swing.GroupLayout(InsertTaskContainer);
        InsertTaskContainer.setLayout(InsertTaskContainerLayout);
        InsertTaskContainerLayout.setHorizontalGroup(
            InsertTaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertTaskHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertTaskContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertTaskFieldsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        InsertTaskContainerLayout.setVerticalGroup(
            InsertTaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTaskContainerLayout.createSequentialGroup()
                .addComponent(InsertTaskHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InsertTaskFieldsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertTaskContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InsertTaskContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertTaskActionContainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertTaskActionContainerMouseClicked

        ValidateFields validateFields = new ValidateFields(
                InsertTaskNameField.getText(),
                InsertTaskDescriptionField.getText(),
                InsertTaskCommentField.getText(),
                InsertTaskDeadlineField.getText());

        try {

            if (validateFields.validateAllField()) {
                Task task = new Task();
                task.setIdProject(project.getId());
                task.setTaskName(InsertTaskNameField.getText());
                task.setTaskDescription(InsertTaskDescriptionField.getText());
                task.setTaskComments(InsertTaskCommentField.getText());
                task.setTaskCompleted(false);

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date deadline;
                deadline = dateFormat.parse(InsertTaskDeadlineField.getText());

                task.setTaskDeadline(deadline);
                taskController.save(task);

                JOptionPane.showMessageDialog(rootPane, "Task saved");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "All fields are requeired");
            }

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(InsertTaskFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_InsertTaskActionContainerMouseClicked

    private void InsertTaskDeadlineFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertTaskDeadlineFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertTaskDeadlineFieldActionPerformed

    private void InsertTaskNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertTaskNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertTaskNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InsertTaskFrame dialog = new InsertTaskFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane InsertTaskActionContainer;
    private javax.swing.JTextArea InsertTaskCommentField;
    private javax.swing.JPanel InsertTaskContainer;
    private javax.swing.JFormattedTextField InsertTaskDeadlineField;
    private javax.swing.JTextArea InsertTaskDescriptionField;
    private javax.swing.JPanel InsertTaskFieldsContainer;
    private javax.swing.JPanel InsertTaskHeader;
    private javax.swing.JTextField InsertTaskNameField;
    private javax.swing.JLabel InsertTaskTitle;
    private javax.swing.JLabel checkIcon;
    private javax.swing.JLabel insertLabel;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }

}
